server:
  port: 5555

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: microservice-api-1
          uri: lb://MICROSERVICE-1
          predicates:
            - Path=/micro-service-1/**
          filters:
            - RewritePath=/micro-service-1/(?<segment>.*), /${segment}

        - id: microservice-api-3
          uri: lb://MICROSERVICE-3
          predicates:
            - Path=/micro-service-3/**
          filters:
            - RewritePath=/micro-service-3/(?<segment>.*), /${segment}
