spring:
  application:
    name: authservice

  datasource:
    url: jdbc:postgresql://localhost:5432/authservicedb
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # or create / create-drop / validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
